# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Derin
tagline:          'Sevenler'
description:      'Just another postdoc''s research page'
url:              http://www.derinsevenler.com
baseurl:          /

# author:
#   name:           'Derin Sevenler'

# paginate:         5

# github:
#   repo:           https://github.com/poole/hyde
